<a href="https://colab.research.google.com/github/FelipeCaetanoSS/Numpy/blob/main/NumpyExercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

***Vetores e Matrizes***

In [3]:
vetorNulo = np.zeros(10)
print(vetorNulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
vetorNulo_quarto1 = np.zeros(10)
vetorNulo_quarto1[3] = 1
print(vetorNulo_quarto1)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [5]:
vetor_10a49 = np.arange(10, 50)
print(vetor_10a49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
matriz_3x3 = np.arange(9).reshape(3, 3)
print(matriz_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


***Mínimo e Máximo***

In [7]:
vetor = np.array([100, 20, 5, 47, 64, 42, 56, 9, 14, 74])

In [8]:
minimo = np.min(vetor)
print("Valor mínimo:", minimo)

Valor mínimo: 5


In [9]:
maximo = np.max(vetor)
print("Valor máximo:", maximo)

Valor máximo: 100


***Matriz identidade***

In [10]:
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***Subtração da média***

In [11]:
matriz = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

media_por_linha = matriz.mean(axis=1, keepdims=True)

matriz_subtraida = matriz - media_por_linha

print(matriz_subtraida)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


***Conceitos Básicos***

In [12]:
import math

In [13]:
raio = 5

area = math.pi * raio ** 2

print("Área do círculo com raio 5:", area)

Área do círculo com raio 5: 78.53981633974483


In [14]:
palavra = "Python"

palavra_invertida = palavra[::-1]

print(palavra)
print(palavra_invertida)

Python
nohtyP


In [1]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

soma_lista = sum(lista)

print(soma_lista)

45


In [21]:
numero = 84

if numero % 2 == 0:
  print(f"O Número é par")

else:
  print(f"O Número é ímpar")

O Número é par


In [22]:
for n in range(1, 11):
  if n == 5:
    continue
  print(n)

1
2
3
4
6
7
8
9
10


In [23]:
def fatorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * fatorial(n - 1)

numero = 5
resultado = fatorial(numero)
print(f"Fatorial de {numero} é {resultado}")


Fatorial de 5 é 120


***Exercícios***

In [28]:
array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

array_invertido = array[::-1]

print(array_invertido)


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [24]:
array = np.array([11, 4, 9, 234, 43, 77, 97, 45, 32])

array_invertido = array[::-1]

print(array_invertido)

[ 32  45  97  77  43 234   9   4  11]


In [25]:
matriz = np.array([[1, 4, 3],
                    [8, 1, 9],
                    [5, 7, 6]])

matriz_inversa = np.linalg.inv(matriz)

print(matriz_inversa)

[[-0.67857143 -0.03571429  0.39285714]
 [-0.03571429 -0.10714286  0.17857143]
 [ 0.60714286  0.1547619  -0.36904762]]


In [26]:
matriz_aleatoria = np.random.rand(5, 5)

min_valor = matriz_aleatoria.min()
max_valor = matriz_aleatoria.max()

print(matriz_aleatoria)
print(min_valor)
print(max_valor)


[[0.06115686 0.61827139 0.59940998 0.63781471 0.11362328]
 [0.97969168 0.40253829 0.43561642 0.08535814 0.40090028]
 [0.60740107 0.67452609 0.95302543 0.96260857 0.75888632]
 [0.27682482 0.35781722 0.88510433 0.60831447 0.19521193]
 [0.35936195 0.77673909 0.99619529 0.80477796 0.62761078]]
0.06115685646141511
0.9961952941123337


In [27]:
matriz_aleatoria = np.random.randint(0, 101, size=(5, 5))

num_maior = np.max(matriz_aleatoria)
num_menor = np.min(matriz_aleatoria)

print(matriz_aleatoria)
print(num_maior)
print(num_menor)

[[40 30 48  0 10]
 [76  1  4 33 73]
 [ 2  6 82 54 68]
 [65 72 88 44 40]
 [70 46 90 62 78]]
90
0
